
#JDBC URL TO CONNECT TO THE DATABASE AND THE USERNAME AND PASSWORD TO CONNECT TO IT
spring.datasource.url=jdbc:mysql://localhost:3306/national_library
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

#THIS WILL HELP HIBERNATE AUTOMATICALLY CREATE AND UPDATE DATABASE TABLES
spring.jpa.hibernate.ddl-auto=update
#THE SQL DIALECT MAKES  HIBERNATE GENERATE BETTER SQL FOR THE CHOOSEN DATABASE
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#spring.mvc.view.suffix=.jsp
#spring.mvc.view.prefix=/pages/

#USED FOR MONTORING HIBERNATE GENERATED SQLS ON THE CONSOLE
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE

# multipart 
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

spring.thymeleaf.cache = false

spring.main.allow-circular-references=true
